import foodFriedRice from "@/assets/food-fried-rice.jpg";
import foodGarlicNoodles from "@/assets/food-garlic-noodles.jpg";
import foodStirFry from "@/assets/food-stir-fry.jpg";
import foodOmelette from "@/assets/food-omelette.jpg";
import foodRamen from "@/assets/food-ramen.jpg";

export interface Recipe {
  id: string;
  title: string;
  author: string;
  authorAvatar: string;
  image: string;
  cookTime: string;
  difficulty: "Easy" | "Medium" | "Hard";
  likes: number;
  comments: number;
  ingredients: { name: string; amount: string }[];
  steps: string[];
  tags: string[];
  source?: "imported" | "ai" | "community" | "scanned";
  cuisine?: string;
}

const images = [foodFriedRice, foodGarlicNoodles, foodStirFry, foodOmelette, foodRamen];
const pick = (i: number) => images[i % images.length];

const authors = [
  { name: "Chef Alex", avatar: "A" }, { name: "Jamie Cooks", avatar: "J" },
  { name: "WokMaster", avatar: "W" }, { name: "BreakfastKing", avatar: "B" },
  { name: "NoodleQueen", avatar: "N" }, { name: "SpiceLord", avatar: "S" },
  { name: "BakeHouse", avatar: "B" }, { name: "GrillGuru", avatar: "G" },
  { name: "TacoMama", avatar: "T" }, { name: "PastaLover", avatar: "P" },
  { name: "CurryKing", avatar: "C" }, { name: "SushiSam", avatar: "S" },
  { name: "VeggieViv", avatar: "V" }, { name: "MeatMike", avatar: "M" },
  { name: "DessertDiva", avatar: "D" },
];

const a = (i: number) => authors[i % authors.length];

const recipeTemplates: Omit<Recipe, "id" | "image" | "author" | "authorAvatar">[] = [
  // 1-5 originals
  { title: "Egg Fried Rice", cookTime: "15 min", difficulty: "Easy", likes: 2340, comments: 189, ingredients: [{ name: "Cooked rice", amount: "3 cups" }, { name: "Eggs", amount: "3" }, { name: "Soy sauce", amount: "2 tbsp" }, { name: "Sesame oil", amount: "1 tsp" }, { name: "Green onions", amount: "3 stalks" }, { name: "Garlic", amount: "2 cloves" }], steps: ["Heat oil in a large wok over high heat", "Scramble eggs and set aside", "Add garlic and fry for 30 seconds", "Add cold rice and stir-fry for 3 minutes", "Add soy sauce and sesame oil", "Toss in eggs and green onions", "Serve hot"], tags: ["Quick", "Asian", "Budget"], cuisine: "Chinese" },
  { title: "Garlic Butter Noodles", cookTime: "20 min", difficulty: "Easy", likes: 4120, comments: 312, ingredients: [{ name: "Spaghetti", amount: "400g" }, { name: "Butter", amount: "4 tbsp" }, { name: "Garlic", amount: "6 cloves" }, { name: "Parmesan", amount: "1/2 cup" }, { name: "Parsley", amount: "2 tbsp" }], steps: ["Cook pasta al dente", "Melt butter, add garlic", "Toss pasta with butter", "Add parmesan, serve"], tags: ["Pasta", "Italian", "Comfort"], cuisine: "Italian" },
  { title: "Chicken Stir Fry", cookTime: "25 min", difficulty: "Medium", likes: 1890, comments: 145, ingredients: [{ name: "Chicken breast", amount: "500g" }, { name: "Bell peppers", amount: "2" }, { name: "Broccoli", amount: "1 head" }, { name: "Soy sauce", amount: "3 tbsp" }, { name: "Oyster sauce", amount: "2 tbsp" }], steps: ["Slice chicken and marinate", "Cut vegetables", "Stir-fry chicken", "Add vegetables", "Season and serve"], tags: ["Healthy", "Asian", "Protein"], cuisine: "Chinese" },
  { title: "Classic Omelette", cookTime: "10 min", difficulty: "Easy", likes: 980, comments: 67, ingredients: [{ name: "Eggs", amount: "3" }, { name: "Butter", amount: "1 tbsp" }, { name: "Cheese", amount: "1/4 cup" }, { name: "Salt & pepper", amount: "To taste" }], steps: ["Beat eggs", "Melt butter", "Pour eggs, let set", "Add cheese, fold, serve"], tags: ["Breakfast", "Quick", "Keto"], cuisine: "French" },
  { title: "Spicy Ramen", cookTime: "30 min", difficulty: "Medium", likes: 5670, comments: 423, ingredients: [{ name: "Ramen noodles", amount: "2 packs" }, { name: "Chicken broth", amount: "4 cups" }, { name: "Soft boiled eggs", amount: "2" }, { name: "Chili paste", amount: "2 tbsp" }], steps: ["Boil broth with chili paste", "Cook noodles", "Soft boil eggs", "Assemble and serve"], tags: ["Japanese", "Spicy", "Soup"], cuisine: "Japanese" },
  // 6-20 Asian
  { title: "Pad Thai", cookTime: "25 min", difficulty: "Medium", likes: 3200, comments: 210, ingredients: [{ name: "Rice noodles", amount: "200g" }, { name: "Shrimp", amount: "200g" }, { name: "Bean sprouts", amount: "1 cup" }, { name: "Tamarind paste", amount: "2 tbsp" }, { name: "Peanuts", amount: "1/4 cup" }], steps: ["Soak noodles", "Cook shrimp", "Make sauce", "Stir fry everything", "Top with peanuts"], tags: ["Thai", "Noodles", "Classic"], cuisine: "Thai" },
  { title: "Chicken Katsu Curry", cookTime: "40 min", difficulty: "Medium", likes: 2800, comments: 195, ingredients: [{ name: "Chicken thigh", amount: "2" }, { name: "Panko breadcrumbs", amount: "1 cup" }, { name: "Curry sauce", amount: "2 cups" }, { name: "Rice", amount: "2 cups" }], steps: ["Bread chicken", "Fry until golden", "Make curry sauce", "Serve over rice"], tags: ["Japanese", "Curry", "Comfort"], cuisine: "Japanese" },
  { title: "Bibimbap", cookTime: "35 min", difficulty: "Medium", likes: 2100, comments: 156, ingredients: [{ name: "Rice", amount: "2 cups" }, { name: "Beef", amount: "200g" }, { name: "Spinach", amount: "1 bunch" }, { name: "Carrots", amount: "2" }, { name: "Gochujang", amount: "2 tbsp" }, { name: "Egg", amount: "1" }], steps: ["Cook rice", "Prep vegetables", "Cook beef", "Fry egg", "Assemble bowl"], tags: ["Korean", "Bowl", "Healthy"], cuisine: "Korean" },
  { title: "Tom Yum Soup", cookTime: "20 min", difficulty: "Easy", likes: 1750, comments: 98, ingredients: [{ name: "Shrimp", amount: "300g" }, { name: "Lemongrass", amount: "2 stalks" }, { name: "Mushrooms", amount: "1 cup" }, { name: "Lime juice", amount: "2 tbsp" }, { name: "Chili", amount: "3" }], steps: ["Boil broth with aromatics", "Add mushrooms", "Add shrimp", "Season and serve"], tags: ["Thai", "Soup", "Spicy"], cuisine: "Thai" },
  { title: "Pho Bo", cookTime: "60 min", difficulty: "Hard", likes: 3400, comments: 267, ingredients: [{ name: "Beef bones", amount: "1 kg" }, { name: "Rice noodles", amount: "300g" }, { name: "Star anise", amount: "3" }, { name: "Cinnamon stick", amount: "1" }, { name: "Bean sprouts", amount: "1 cup" }], steps: ["Simmer bones for broth", "Toast spices", "Cook noodles", "Assemble bowls", "Add fresh herbs"], tags: ["Vietnamese", "Soup", "Classic"], cuisine: "Vietnamese" },
  { title: "Gyoza", cookTime: "30 min", difficulty: "Medium", likes: 2600, comments: 178, ingredients: [{ name: "Ground pork", amount: "300g" }, { name: "Cabbage", amount: "2 cups" }, { name: "Gyoza wrappers", amount: "30" }, { name: "Ginger", amount: "1 tbsp" }, { name: "Soy sauce", amount: "2 tbsp" }], steps: ["Mix filling", "Wrap dumplings", "Pan fry until crispy", "Add water and steam", "Serve with dipping sauce"], tags: ["Japanese", "Dumplings", "Snack"], cuisine: "Japanese" },
  { title: "Mapo Tofu", cookTime: "20 min", difficulty: "Easy", likes: 1900, comments: 134, ingredients: [{ name: "Silken tofu", amount: "400g" }, { name: "Ground pork", amount: "150g" }, { name: "Doubanjiang", amount: "2 tbsp" }, { name: "Sichuan peppercorns", amount: "1 tsp" }], steps: ["Cook pork with doubanjiang", "Add tofu gently", "Season with peppercorns", "Serve over rice"], tags: ["Chinese", "Spicy", "Tofu"], cuisine: "Chinese" },
  { title: "Chicken Teriyaki", cookTime: "20 min", difficulty: "Easy", likes: 3100, comments: 201, ingredients: [{ name: "Chicken thighs", amount: "4" }, { name: "Soy sauce", amount: "3 tbsp" }, { name: "Mirin", amount: "2 tbsp" }, { name: "Sugar", amount: "1 tbsp" }, { name: "Rice", amount: "2 cups" }], steps: ["Make teriyaki sauce", "Grill chicken", "Glaze with sauce", "Serve with rice"], tags: ["Japanese", "Grilled", "Quick"], cuisine: "Japanese" },
  { title: "Spring Rolls", cookTime: "15 min", difficulty: "Easy", likes: 1400, comments: 89, ingredients: [{ name: "Rice paper", amount: "12" }, { name: "Shrimp", amount: "12" }, { name: "Vermicelli", amount: "100g" }, { name: "Lettuce", amount: "6 leaves" }, { name: "Mint", amount: "1 bunch" }], steps: ["Cook shrimp and noodles", "Soften rice paper", "Add fillings", "Roll tightly", "Serve with peanut sauce"], tags: ["Vietnamese", "Fresh", "Light"], cuisine: "Vietnamese" },
  { title: "Kung Pao Chicken", cookTime: "25 min", difficulty: "Medium", likes: 2700, comments: 188, ingredients: [{ name: "Chicken breast", amount: "400g" }, { name: "Peanuts", amount: "1/3 cup" }, { name: "Dried chilis", amount: "8" }, { name: "Soy sauce", amount: "2 tbsp" }, { name: "Vinegar", amount: "1 tbsp" }], steps: ["Cube and marinate chicken", "Fry chilis and peanuts", "Cook chicken", "Add sauce", "Toss and serve"], tags: ["Chinese", "Spicy", "Classic"], cuisine: "Chinese" },
  // 16-30 Italian/Mediterranean
  { title: "Margherita Pizza", cookTime: "25 min", difficulty: "Medium", likes: 4500, comments: 340, ingredients: [{ name: "Pizza dough", amount: "1 ball" }, { name: "San Marzano tomatoes", amount: "1 can" }, { name: "Fresh mozzarella", amount: "200g" }, { name: "Basil", amount: "1 bunch" }], steps: ["Stretch dough", "Add sauce", "Top with mozzarella", "Bake at 500°F", "Add fresh basil"], tags: ["Italian", "Pizza", "Classic"], cuisine: "Italian" },
  { title: "Carbonara", cookTime: "20 min", difficulty: "Medium", likes: 5200, comments: 398, ingredients: [{ name: "Spaghetti", amount: "400g" }, { name: "Guanciale", amount: "200g" }, { name: "Egg yolks", amount: "4" }, { name: "Pecorino", amount: "1 cup" }, { name: "Black pepper", amount: "2 tsp" }], steps: ["Cook pasta", "Crisp guanciale", "Mix eggs and cheese", "Toss hot pasta with egg mixture", "Season generously"], tags: ["Italian", "Pasta", "Classic"], cuisine: "Italian" },
  { title: "Risotto ai Funghi", cookTime: "35 min", difficulty: "Medium", likes: 2300, comments: 167, ingredients: [{ name: "Arborio rice", amount: "300g" }, { name: "Mixed mushrooms", amount: "300g" }, { name: "White wine", amount: "1/2 cup" }, { name: "Parmesan", amount: "1/2 cup" }, { name: "Butter", amount: "2 tbsp" }], steps: ["Sauté mushrooms", "Toast rice", "Add wine", "Gradually add broth", "Finish with butter and parmesan"], tags: ["Italian", "Rice", "Elegant"], cuisine: "Italian" },
  { title: "Greek Salad", cookTime: "10 min", difficulty: "Easy", likes: 1600, comments: 78, ingredients: [{ name: "Tomatoes", amount: "4" }, { name: "Cucumber", amount: "1" }, { name: "Red onion", amount: "1" }, { name: "Feta cheese", amount: "200g" }, { name: "Kalamata olives", amount: "1/2 cup" }], steps: ["Chop vegetables", "Add olives and feta", "Dress with olive oil and oregano", "Toss gently"], tags: ["Greek", "Salad", "Fresh"], cuisine: "Greek" },
  { title: "Shakshuka", cookTime: "25 min", difficulty: "Easy", likes: 2900, comments: 203, ingredients: [{ name: "Eggs", amount: "6" }, { name: "Canned tomatoes", amount: "2 cans" }, { name: "Bell pepper", amount: "1" }, { name: "Cumin", amount: "1 tsp" }, { name: "Feta", amount: "100g" }], steps: ["Sauté peppers and onions", "Add tomatoes and spices", "Create wells for eggs", "Poach eggs", "Top with feta"], tags: ["Mediterranean", "Breakfast", "One-pan"], cuisine: "Middle Eastern" },
  { title: "Hummus", cookTime: "10 min", difficulty: "Easy", likes: 1200, comments: 56, ingredients: [{ name: "Chickpeas", amount: "2 cans" }, { name: "Tahini", amount: "1/4 cup" }, { name: "Lemon juice", amount: "3 tbsp" }, { name: "Garlic", amount: "2 cloves" }], steps: ["Blend chickpeas", "Add tahini, lemon, garlic", "Season and drizzle with olive oil"], tags: ["Mediterranean", "Dip", "Vegan"], cuisine: "Lebanese" },
  { title: "Caprese Salad", cookTime: "5 min", difficulty: "Easy", likes: 1800, comments: 92, ingredients: [{ name: "Fresh mozzarella", amount: "300g" }, { name: "Tomatoes", amount: "4" }, { name: "Basil", amount: "1 bunch" }, { name: "Balsamic glaze", amount: "2 tbsp" }], steps: ["Slice mozzarella and tomatoes", "Layer alternating", "Add basil", "Drizzle with balsamic"], tags: ["Italian", "Salad", "No-cook"], cuisine: "Italian" },
  { title: "Moussaka", cookTime: "60 min", difficulty: "Hard", likes: 1500, comments: 112, ingredients: [{ name: "Eggplant", amount: "2" }, { name: "Ground lamb", amount: "500g" }, { name: "Béchamel sauce", amount: "2 cups" }, { name: "Tomato sauce", amount: "1 cup" }], steps: ["Slice and roast eggplant", "Cook meat sauce", "Layer in dish", "Top with béchamel", "Bake until golden"], tags: ["Greek", "Casserole", "Hearty"], cuisine: "Greek" },
  // 24-40 Mexican/Latin
  { title: "Street Tacos", cookTime: "20 min", difficulty: "Easy", likes: 3800, comments: 256, ingredients: [{ name: "Corn tortillas", amount: "12" }, { name: "Carne asada", amount: "500g" }, { name: "Cilantro", amount: "1 bunch" }, { name: "Onion", amount: "1" }, { name: "Lime", amount: "3" }], steps: ["Season and grill meat", "Warm tortillas", "Dice onion and cilantro", "Assemble tacos", "Squeeze lime"], tags: ["Mexican", "Street food", "Quick"], cuisine: "Mexican" },
  { title: "Guacamole", cookTime: "10 min", difficulty: "Easy", likes: 2100, comments: 134, ingredients: [{ name: "Avocados", amount: "3" }, { name: "Lime", amount: "2" }, { name: "Cilantro", amount: "1/4 cup" }, { name: "Jalapeño", amount: "1" }, { name: "Tomato", amount: "1" }], steps: ["Mash avocados", "Add lime juice", "Mix in diced tomato, onion, cilantro", "Season"], tags: ["Mexican", "Dip", "Fresh"], cuisine: "Mexican" },
  { title: "Chicken Enchiladas", cookTime: "40 min", difficulty: "Medium", likes: 2600, comments: 178, ingredients: [{ name: "Tortillas", amount: "8" }, { name: "Shredded chicken", amount: "3 cups" }, { name: "Enchilada sauce", amount: "2 cups" }, { name: "Cheese", amount: "2 cups" }], steps: ["Fill tortillas with chicken", "Roll and place in dish", "Cover with sauce and cheese", "Bake until bubbly"], tags: ["Mexican", "Baked", "Comfort"], cuisine: "Mexican" },
  { title: "Ceviche", cookTime: "30 min", difficulty: "Easy", likes: 1700, comments: 98, ingredients: [{ name: "White fish", amount: "500g" }, { name: "Lime juice", amount: "1 cup" }, { name: "Red onion", amount: "1" }, { name: "Cilantro", amount: "1/2 cup" }, { name: "Avocado", amount: "1" }], steps: ["Dice fish", "Marinate in lime juice", "Add vegetables", "Chill 20 minutes", "Serve with chips"], tags: ["Peruvian", "Seafood", "Fresh"], cuisine: "Peruvian" },
  { title: "Black Bean Soup", cookTime: "35 min", difficulty: "Easy", likes: 1300, comments: 76, ingredients: [{ name: "Black beans", amount: "2 cans" }, { name: "Onion", amount: "1" }, { name: "Cumin", amount: "1 tbsp" }, { name: "Chipotle peppers", amount: "2" }], steps: ["Sauté onion", "Add beans and spices", "Simmer 20 minutes", "Blend partially", "Serve with sour cream"], tags: ["Mexican", "Soup", "Vegan"], cuisine: "Mexican" },
  { title: "Empanadas", cookTime: "45 min", difficulty: "Medium", likes: 2000, comments: 145, ingredients: [{ name: "Empanada dough", amount: "12" }, { name: "Ground beef", amount: "300g" }, { name: "Olives", amount: "1/4 cup" }, { name: "Hard boiled eggs", amount: "2" }], steps: ["Cook filling", "Fill dough circles", "Fold and crimp", "Bake until golden"], tags: ["Argentine", "Pastry", "Snack"], cuisine: "Argentine" },
  { title: "Elote (Street Corn)", cookTime: "15 min", difficulty: "Easy", likes: 2400, comments: 167, ingredients: [{ name: "Corn on the cob", amount: "4" }, { name: "Mayo", amount: "1/4 cup" }, { name: "Cotija cheese", amount: "1/2 cup" }, { name: "Chili powder", amount: "1 tsp" }, { name: "Lime", amount: "2" }], steps: ["Grill corn", "Spread mayo", "Roll in cheese", "Sprinkle chili", "Squeeze lime"], tags: ["Mexican", "Street food", "Grilled"], cuisine: "Mexican" },
  { title: "Churros", cookTime: "30 min", difficulty: "Medium", likes: 3500, comments: 234, ingredients: [{ name: "Flour", amount: "1 cup" }, { name: "Butter", amount: "2 tbsp" }, { name: "Sugar", amount: "1/2 cup" }, { name: "Cinnamon", amount: "1 tbsp" }, { name: "Chocolate sauce", amount: "1/2 cup" }], steps: ["Make choux dough", "Pipe into strips", "Fry until golden", "Roll in cinnamon sugar", "Serve with chocolate"], tags: ["Mexican", "Dessert", "Sweet"], cuisine: "Mexican" },
  // 32-45 Indian
  { title: "Butter Chicken", cookTime: "40 min", difficulty: "Medium", likes: 4800, comments: 356, ingredients: [{ name: "Chicken thighs", amount: "600g" }, { name: "Tomato sauce", amount: "2 cups" }, { name: "Cream", amount: "1/2 cup" }, { name: "Butter", amount: "3 tbsp" }, { name: "Garam masala", amount: "2 tsp" }], steps: ["Marinate chicken in yogurt", "Cook chicken", "Make creamy tomato sauce", "Combine and simmer", "Serve with naan"], tags: ["Indian", "Curry", "Creamy"], cuisine: "Indian" },
  { title: "Palak Paneer", cookTime: "30 min", difficulty: "Medium", likes: 2200, comments: 156, ingredients: [{ name: "Spinach", amount: "500g" }, { name: "Paneer", amount: "200g" }, { name: "Onion", amount: "1" }, { name: "Cream", amount: "2 tbsp" }, { name: "Cumin", amount: "1 tsp" }], steps: ["Blanch and blend spinach", "Fry paneer cubes", "Make base sauce", "Add spinach purée", "Add paneer and cream"], tags: ["Indian", "Vegetarian", "Healthy"], cuisine: "Indian" },
  { title: "Chicken Tikka Masala", cookTime: "45 min", difficulty: "Medium", likes: 5100, comments: 389, ingredients: [{ name: "Chicken", amount: "600g" }, { name: "Yogurt", amount: "1 cup" }, { name: "Tomato purée", amount: "2 cups" }, { name: "Cream", amount: "1/2 cup" }, { name: "Tikka paste", amount: "3 tbsp" }], steps: ["Marinate chicken in yogurt and spices", "Grill chicken", "Make masala sauce", "Combine", "Serve with rice"], tags: ["Indian", "Curry", "Popular"], cuisine: "Indian" },
  { title: "Samosas", cookTime: "45 min", difficulty: "Medium", likes: 1800, comments: 123, ingredients: [{ name: "Potatoes", amount: "3" }, { name: "Peas", amount: "1/2 cup" }, { name: "Pastry sheets", amount: "6" }, { name: "Cumin", amount: "1 tsp" }, { name: "Garam masala", amount: "1 tsp" }], steps: ["Boil and mash potatoes", "Cook filling with spices", "Wrap in pastry", "Deep fry until golden", "Serve with chutney"], tags: ["Indian", "Snack", "Fried"], cuisine: "Indian" },
  { title: "Dal Tadka", cookTime: "30 min", difficulty: "Easy", likes: 1600, comments: 98, ingredients: [{ name: "Red lentils", amount: "1 cup" }, { name: "Tomatoes", amount: "2" }, { name: "Cumin seeds", amount: "1 tsp" }, { name: "Turmeric", amount: "1/2 tsp" }, { name: "Ghee", amount: "2 tbsp" }], steps: ["Cook lentils until soft", "Make tadka with spices", "Pour over dal", "Garnish with cilantro", "Serve with rice"], tags: ["Indian", "Lentils", "Vegan"], cuisine: "Indian" },
  { title: "Biryani", cookTime: "60 min", difficulty: "Hard", likes: 4200, comments: 312, ingredients: [{ name: "Basmati rice", amount: "2 cups" }, { name: "Chicken", amount: "500g" }, { name: "Yogurt", amount: "1 cup" }, { name: "Saffron", amount: "1 pinch" }, { name: "Fried onions", amount: "1 cup" }], steps: ["Marinate chicken", "Par-cook rice", "Layer chicken and rice", "Add saffron milk", "Dum cook 25 minutes"], tags: ["Indian", "Rice", "Festive"], cuisine: "Indian" },
  { title: "Naan Bread", cookTime: "25 min", difficulty: "Easy", likes: 2800, comments: 189, ingredients: [{ name: "Flour", amount: "2 cups" }, { name: "Yogurt", amount: "1/2 cup" }, { name: "Yeast", amount: "1 tsp" }, { name: "Butter", amount: "2 tbsp" }, { name: "Garlic", amount: "3 cloves" }], steps: ["Make dough", "Let rise 1 hour", "Roll out", "Cook in hot pan", "Brush with garlic butter"], tags: ["Indian", "Bread", "Side"], cuisine: "Indian" },
  { title: "Chana Masala", cookTime: "30 min", difficulty: "Easy", likes: 1900, comments: 134, ingredients: [{ name: "Chickpeas", amount: "2 cans" }, { name: "Tomatoes", amount: "3" }, { name: "Ginger", amount: "1 inch" }, { name: "Garam masala", amount: "1 tsp" }], steps: ["Sauté onions and spices", "Add tomatoes", "Add chickpeas", "Simmer 15 minutes", "Garnish and serve"], tags: ["Indian", "Vegan", "Protein"], cuisine: "Indian" },
  // 40-55 American/Comfort
  { title: "Smash Burger", cookTime: "15 min", difficulty: "Easy", likes: 5800, comments: 445, ingredients: [{ name: "Ground beef", amount: "400g" }, { name: "Burger buns", amount: "4" }, { name: "American cheese", amount: "4 slices" }, { name: "Pickles", amount: "8" }, { name: "Special sauce", amount: "4 tbsp" }], steps: ["Form loose balls", "Smash on hot griddle", "Season immediately", "Add cheese to melt", "Assemble burger"], tags: ["American", "Burger", "Classic"], cuisine: "American" },
  { title: "Mac and Cheese", cookTime: "25 min", difficulty: "Easy", likes: 3400, comments: 234, ingredients: [{ name: "Elbow macaroni", amount: "400g" }, { name: "Sharp cheddar", amount: "3 cups" }, { name: "Milk", amount: "2 cups" }, { name: "Butter", amount: "3 tbsp" }, { name: "Flour", amount: "2 tbsp" }], steps: ["Cook pasta", "Make roux", "Add milk and cheese", "Combine with pasta", "Bake until bubbly"], tags: ["American", "Comfort", "Cheese"], cuisine: "American" },
  { title: "BBQ Pulled Pork", cookTime: "240 min", difficulty: "Medium", likes: 3100, comments: 212, ingredients: [{ name: "Pork shoulder", amount: "2 kg" }, { name: "BBQ sauce", amount: "2 cups" }, { name: "Brown sugar", amount: "1/4 cup" }, { name: "Paprika", amount: "2 tbsp" }], steps: ["Rub pork with spices", "Slow cook 4 hours", "Shred meat", "Mix with BBQ sauce", "Serve on buns"], tags: ["American", "BBQ", "Slow-cook"], cuisine: "American" },
  { title: "Clam Chowder", cookTime: "35 min", difficulty: "Medium", likes: 1700, comments: 112, ingredients: [{ name: "Clams", amount: "2 cans" }, { name: "Potatoes", amount: "3" }, { name: "Bacon", amount: "4 strips" }, { name: "Cream", amount: "1 cup" }, { name: "Celery", amount: "2 stalks" }], steps: ["Cook bacon", "Sauté vegetables", "Add potatoes and broth", "Add clams and cream", "Simmer until thick"], tags: ["American", "Soup", "Seafood"], cuisine: "American" },
  { title: "Buffalo Wings", cookTime: "35 min", difficulty: "Easy", likes: 4100, comments: 298, ingredients: [{ name: "Chicken wings", amount: "1 kg" }, { name: "Hot sauce", amount: "1/2 cup" }, { name: "Butter", amount: "4 tbsp" }, { name: "Celery sticks", amount: "6" }, { name: "Blue cheese dip", amount: "1 cup" }], steps: ["Bake wings at 425°F", "Mix hot sauce and butter", "Toss wings in sauce", "Serve with celery and dip"], tags: ["American", "Wings", "Spicy"], cuisine: "American" },
  { title: "Pancakes", cookTime: "15 min", difficulty: "Easy", likes: 2600, comments: 167, ingredients: [{ name: "Flour", amount: "1.5 cups" }, { name: "Milk", amount: "1 cup" }, { name: "Eggs", amount: "2" }, { name: "Butter", amount: "2 tbsp" }, { name: "Maple syrup", amount: "1/4 cup" }], steps: ["Mix dry ingredients", "Add wet ingredients", "Cook on griddle", "Flip when bubbly", "Stack and serve with syrup"], tags: ["American", "Breakfast", "Sweet"], cuisine: "American" },
  { title: "Grilled Cheese", cookTime: "10 min", difficulty: "Easy", likes: 2200, comments: 123, ingredients: [{ name: "Bread", amount: "4 slices" }, { name: "Cheddar", amount: "4 slices" }, { name: "Butter", amount: "2 tbsp" }, { name: "Tomato soup", amount: "2 cups" }], steps: ["Butter bread", "Add cheese", "Grill until golden", "Serve with tomato soup"], tags: ["American", "Sandwich", "Quick"], cuisine: "American" },
  { title: "Chicken Pot Pie", cookTime: "50 min", difficulty: "Medium", likes: 1900, comments: 145, ingredients: [{ name: "Chicken", amount: "2 cups" }, { name: "Mixed vegetables", amount: "2 cups" }, { name: "Puff pastry", amount: "1 sheet" }, { name: "Cream", amount: "1 cup" }], steps: ["Cook filling", "Pour into baking dish", "Top with pastry", "Bake until golden"], tags: ["American", "Comfort", "Baked"], cuisine: "American" },
  // 48-60 Middle Eastern
  { title: "Falafel", cookTime: "30 min", difficulty: "Medium", likes: 2500, comments: 178, ingredients: [{ name: "Chickpeas", amount: "2 cups" }, { name: "Parsley", amount: "1 cup" }, { name: "Cumin", amount: "1 tsp" }, { name: "Garlic", amount: "4 cloves" }], steps: ["Soak chickpeas overnight", "Blend with herbs", "Form balls", "Deep fry", "Serve in pita"], tags: ["Middle Eastern", "Vegan", "Street food"], cuisine: "Lebanese" },
  { title: "Shawarma", cookTime: "30 min", difficulty: "Medium", likes: 3600, comments: 245, ingredients: [{ name: "Chicken thighs", amount: "600g" }, { name: "Shawarma spice", amount: "2 tbsp" }, { name: "Pita bread", amount: "4" }, { name: "Tahini sauce", amount: "1/2 cup" }, { name: "Pickles", amount: "1/2 cup" }], steps: ["Marinate chicken", "Grill or roast", "Slice thinly", "Assemble in pita", "Add pickles and sauce"], tags: ["Middle Eastern", "Wrap", "Grilled"], cuisine: "Lebanese" },
  { title: "Tabbouleh", cookTime: "15 min", difficulty: "Easy", likes: 1100, comments: 67, ingredients: [{ name: "Bulgur wheat", amount: "1/2 cup" }, { name: "Parsley", amount: "2 cups" }, { name: "Tomatoes", amount: "3" }, { name: "Lemon juice", amount: "1/4 cup" }, { name: "Mint", amount: "1/4 cup" }], steps: ["Soak bulgur", "Chop parsley and mint", "Dice tomatoes", "Mix all", "Dress with lemon and oil"], tags: ["Lebanese", "Salad", "Fresh"], cuisine: "Lebanese" },
  { title: "Lamb Kofta", cookTime: "25 min", difficulty: "Easy", likes: 2000, comments: 145, ingredients: [{ name: "Ground lamb", amount: "500g" }, { name: "Onion", amount: "1" }, { name: "Cumin", amount: "1 tsp" }, { name: "Parsley", amount: "1/4 cup" }], steps: ["Mix lamb with spices", "Form onto skewers", "Grill 8 minutes", "Serve with yogurt"], tags: ["Middle Eastern", "Grilled", "Protein"], cuisine: "Turkish" },
  { title: "Baklava", cookTime: "60 min", difficulty: "Hard", likes: 2800, comments: 198, ingredients: [{ name: "Phyllo dough", amount: "1 pack" }, { name: "Walnuts", amount: "2 cups" }, { name: "Butter", amount: "1 cup" }, { name: "Honey syrup", amount: "1.5 cups" }], steps: ["Layer phyllo with butter", "Add nut filling", "Cut into diamonds", "Bake until golden", "Pour syrup over"], tags: ["Middle Eastern", "Dessert", "Sweet"], cuisine: "Turkish" },
  // 53-65 French
  { title: "Croque Monsieur", cookTime: "15 min", difficulty: "Easy", likes: 1800, comments: 112, ingredients: [{ name: "Bread", amount: "4 slices" }, { name: "Ham", amount: "4 slices" }, { name: "Gruyère", amount: "1 cup" }, { name: "Béchamel", amount: "1/2 cup" }], steps: ["Spread béchamel on bread", "Add ham and cheese", "Top with more cheese", "Broil until bubbly"], tags: ["French", "Sandwich", "Classic"], cuisine: "French" },
  { title: "French Onion Soup", cookTime: "50 min", difficulty: "Medium", likes: 2700, comments: 189, ingredients: [{ name: "Onions", amount: "6" }, { name: "Beef broth", amount: "4 cups" }, { name: "Baguette", amount: "4 slices" }, { name: "Gruyère", amount: "1 cup" }, { name: "Butter", amount: "3 tbsp" }], steps: ["Caramelize onions slowly", "Add broth and simmer", "Ladle into bowls", "Top with bread and cheese", "Broil until melted"], tags: ["French", "Soup", "Comfort"], cuisine: "French" },
  { title: "Ratatouille", cookTime: "45 min", difficulty: "Medium", likes: 2100, comments: 156, ingredients: [{ name: "Eggplant", amount: "1" }, { name: "Zucchini", amount: "2" }, { name: "Bell pepper", amount: "2" }, { name: "Tomatoes", amount: "4" }, { name: "Herbs de Provence", amount: "1 tbsp" }], steps: ["Slice vegetables thinly", "Make tomato base", "Layer vegetables", "Bake 40 minutes", "Drizzle with olive oil"], tags: ["French", "Vegetarian", "Elegant"], cuisine: "French" },
  { title: "Crème Brûlée", cookTime: "50 min", difficulty: "Medium", likes: 3200, comments: 234, ingredients: [{ name: "Heavy cream", amount: "2 cups" }, { name: "Egg yolks", amount: "5" }, { name: "Sugar", amount: "1/2 cup" }, { name: "Vanilla", amount: "1 bean" }], steps: ["Heat cream with vanilla", "Whisk yolks and sugar", "Combine and strain", "Bake in water bath", "Torch sugar on top"], tags: ["French", "Dessert", "Elegant"], cuisine: "French" },
  { title: "Quiche Lorraine", cookTime: "45 min", difficulty: "Medium", likes: 1700, comments: 112, ingredients: [{ name: "Pie crust", amount: "1" }, { name: "Bacon", amount: "6 strips" }, { name: "Gruyère", amount: "1 cup" }, { name: "Eggs", amount: "4" }, { name: "Cream", amount: "1 cup" }], steps: ["Blind bake crust", "Cook bacon", "Layer bacon and cheese", "Pour egg mixture", "Bake 35 minutes"], tags: ["French", "Brunch", "Baked"], cuisine: "French" },
  { title: "Coq au Vin", cookTime: "90 min", difficulty: "Hard", likes: 2400, comments: 167, ingredients: [{ name: "Chicken pieces", amount: "1 whole" }, { name: "Red wine", amount: "2 cups" }, { name: "Mushrooms", amount: "200g" }, { name: "Pearl onions", amount: "12" }, { name: "Bacon", amount: "4 strips" }], steps: ["Brown chicken", "Cook bacon and vegetables", "Deglaze with wine", "Braise chicken in wine", "Simmer until tender"], tags: ["French", "Braised", "Classic"], cuisine: "French" },
  // 59-75 Korean
  { title: "Korean Fried Chicken", cookTime: "35 min", difficulty: "Medium", likes: 4600, comments: 334, ingredients: [{ name: "Chicken wings", amount: "1 kg" }, { name: "Gochujang", amount: "3 tbsp" }, { name: "Honey", amount: "2 tbsp" }, { name: "Soy sauce", amount: "2 tbsp" }, { name: "Cornstarch", amount: "1 cup" }], steps: ["Double coat in cornstarch", "Fry twice for extra crisp", "Make glaze", "Toss wings in glaze", "Garnish with sesame"], tags: ["Korean", "Fried", "Crispy"], cuisine: "Korean" },
  { title: "Japchae", cookTime: "25 min", difficulty: "Medium", likes: 1900, comments: 134, ingredients: [{ name: "Glass noodles", amount: "200g" }, { name: "Beef", amount: "150g" }, { name: "Spinach", amount: "1 bunch" }, { name: "Carrots", amount: "1" }, { name: "Sesame oil", amount: "2 tbsp" }], steps: ["Cook noodles", "Stir fry vegetables separately", "Cook beef", "Toss everything together", "Season with soy and sesame"], tags: ["Korean", "Noodles", "Festive"], cuisine: "Korean" },
  { title: "Kimchi Jjigae", cookTime: "30 min", difficulty: "Easy", likes: 2300, comments: 167, ingredients: [{ name: "Aged kimchi", amount: "2 cups" }, { name: "Pork belly", amount: "200g" }, { name: "Tofu", amount: "200g" }, { name: "Gochugaru", amount: "1 tbsp" }], steps: ["Sauté kimchi and pork", "Add water and simmer", "Add tofu", "Crack egg on top", "Serve bubbling hot"], tags: ["Korean", "Stew", "Spicy"], cuisine: "Korean" },
  { title: "Tteokbokki", cookTime: "20 min", difficulty: "Easy", likes: 3100, comments: 212, ingredients: [{ name: "Rice cakes", amount: "400g" }, { name: "Gochujang", amount: "2 tbsp" }, { name: "Fish cakes", amount: "200g" }, { name: "Sugar", amount: "1 tbsp" }], steps: ["Boil water", "Add gochujang and sugar", "Add rice cakes", "Cook until chewy", "Add fish cakes"], tags: ["Korean", "Street food", "Spicy"], cuisine: "Korean" },
  { title: "Korean BBQ Beef", cookTime: "20 min", difficulty: "Easy", likes: 3800, comments: 267, ingredients: [{ name: "Beef short ribs", amount: "500g" }, { name: "Soy sauce", amount: "1/4 cup" }, { name: "Pear juice", amount: "2 tbsp" }, { name: "Garlic", amount: "4 cloves" }, { name: "Sesame oil", amount: "1 tbsp" }], steps: ["Marinate beef 2 hours", "Grill on high heat", "Wrap in lettuce", "Add ssamjang", "Enjoy with banchan"], tags: ["Korean", "BBQ", "Grilled"], cuisine: "Korean" },
  // 64-80 Southeast Asian
  { title: "Nasi Goreng", cookTime: "15 min", difficulty: "Easy", likes: 2400, comments: 167, ingredients: [{ name: "Cooked rice", amount: "3 cups" }, { name: "Kecap manis", amount: "2 tbsp" }, { name: "Shrimp paste", amount: "1 tsp" }, { name: "Egg", amount: "2" }, { name: "Shallots", amount: "4" }], steps: ["Fry shallots and paste", "Add rice", "Season with kecap manis", "Fry egg sunny side up", "Top rice with egg"], tags: ["Indonesian", "Rice", "Quick"], cuisine: "Indonesian" },
  { title: "Laksa", cookTime: "35 min", difficulty: "Medium", likes: 2700, comments: 189, ingredients: [{ name: "Rice noodles", amount: "200g" }, { name: "Coconut milk", amount: "2 cups" }, { name: "Laksa paste", amount: "3 tbsp" }, { name: "Shrimp", amount: "200g" }, { name: "Bean sprouts", amount: "1 cup" }], steps: ["Make laksa broth", "Cook noodles", "Poach shrimp", "Assemble bowls", "Garnish with herbs"], tags: ["Malaysian", "Soup", "Spicy"], cuisine: "Malaysian" },
  { title: "Green Curry", cookTime: "30 min", difficulty: "Medium", likes: 3500, comments: 234, ingredients: [{ name: "Chicken", amount: "400g" }, { name: "Coconut milk", amount: "2 cans" }, { name: "Green curry paste", amount: "3 tbsp" }, { name: "Thai basil", amount: "1 cup" }, { name: "Bamboo shoots", amount: "1 cup" }], steps: ["Fry curry paste", "Add coconut milk", "Add chicken", "Simmer 15 minutes", "Add basil and serve"], tags: ["Thai", "Curry", "Coconut"], cuisine: "Thai" },
  { title: "Satay Chicken", cookTime: "25 min", difficulty: "Easy", likes: 2100, comments: 145, ingredients: [{ name: "Chicken thighs", amount: "500g" }, { name: "Peanut butter", amount: "1/4 cup" }, { name: "Coconut milk", amount: "1/2 cup" }, { name: "Turmeric", amount: "1 tsp" }, { name: "Lemongrass", amount: "1 stalk" }], steps: ["Marinate chicken", "Thread onto skewers", "Grill until charred", "Make peanut sauce", "Serve with sauce"], tags: ["Thai", "Grilled", "Skewer"], cuisine: "Thai" },
  { title: "Mango Sticky Rice", cookTime: "30 min", difficulty: "Easy", likes: 2800, comments: 198, ingredients: [{ name: "Sticky rice", amount: "1 cup" }, { name: "Coconut milk", amount: "1 cup" }, { name: "Mango", amount: "2" }, { name: "Sugar", amount: "3 tbsp" }], steps: ["Steam sticky rice", "Make coconut sauce", "Pour over rice", "Slice mango", "Arrange and serve"], tags: ["Thai", "Dessert", "Sweet"], cuisine: "Thai" },
  { title: "Rendang", cookTime: "120 min", difficulty: "Hard", likes: 3200, comments: 223, ingredients: [{ name: "Beef chuck", amount: "1 kg" }, { name: "Coconut milk", amount: "3 cups" }, { name: "Lemongrass", amount: "3 stalks" }, { name: "Galangal", amount: "2 inches" }, { name: "Chili paste", amount: "3 tbsp" }], steps: ["Blend spice paste", "Brown beef", "Add coconut milk", "Simmer slowly 2 hours", "Cook until dry and dark"], tags: ["Indonesian", "Slow-cook", "Rich"], cuisine: "Indonesian" },
  { title: "Banh Mi", cookTime: "20 min", difficulty: "Easy", likes: 2600, comments: 178, ingredients: [{ name: "Baguette", amount: "2" }, { name: "Pork", amount: "200g" }, { name: "Pickled daikon", amount: "1/2 cup" }, { name: "Cilantro", amount: "1 bunch" }, { name: "Jalapeño", amount: "1" }], steps: ["Cook pork", "Warm baguette", "Spread pâté", "Layer meat and pickles", "Add cilantro and jalapeño"], tags: ["Vietnamese", "Sandwich", "Fresh"], cuisine: "Vietnamese" },
  // 71-85 Breakfast & Brunch
  { title: "Avocado Toast", cookTime: "5 min", difficulty: "Easy", likes: 3200, comments: 212, ingredients: [{ name: "Sourdough", amount: "2 slices" }, { name: "Avocado", amount: "1" }, { name: "Lemon", amount: "1/2" }, { name: "Red pepper flakes", amount: "1/2 tsp" }, { name: "Everything seasoning", amount: "1 tsp" }], steps: ["Toast bread", "Mash avocado with lemon", "Spread on toast", "Season and top"], tags: ["Breakfast", "Quick", "Healthy"], cuisine: "American" },
  { title: "Eggs Benedict", cookTime: "25 min", difficulty: "Medium", likes: 2800, comments: 189, ingredients: [{ name: "English muffins", amount: "2" }, { name: "Eggs", amount: "4" }, { name: "Ham", amount: "4 slices" }, { name: "Hollandaise", amount: "1 cup" }], steps: ["Toast muffins", "Warm ham", "Poach eggs", "Assemble stacks", "Pour hollandaise over"], tags: ["Brunch", "Classic", "Eggs"], cuisine: "American" },
  { title: "Açaí Bowl", cookTime: "10 min", difficulty: "Easy", likes: 2400, comments: 167, ingredients: [{ name: "Frozen açaí", amount: "2 packs" }, { name: "Banana", amount: "1" }, { name: "Granola", amount: "1/2 cup" }, { name: "Berries", amount: "1/2 cup" }, { name: "Honey", amount: "1 tbsp" }], steps: ["Blend açaí and banana", "Pour into bowl", "Top with granola", "Add berries", "Drizzle honey"], tags: ["Breakfast", "Healthy", "Bowl"], cuisine: "Brazilian" },
  { title: "Banana Bread", cookTime: "60 min", difficulty: "Easy", likes: 3100, comments: 212, ingredients: [{ name: "Ripe bananas", amount: "3" }, { name: "Flour", amount: "1.5 cups" }, { name: "Sugar", amount: "3/4 cup" }, { name: "Butter", amount: "1/3 cup" }, { name: "Eggs", amount: "2" }], steps: ["Mash bananas", "Mix wet ingredients", "Fold in dry ingredients", "Pour into loaf pan", "Bake 55 minutes at 350°F"], tags: ["Baking", "Sweet", "Classic"], cuisine: "American" },
  { title: "French Toast", cookTime: "15 min", difficulty: "Easy", likes: 2600, comments: 178, ingredients: [{ name: "Brioche", amount: "6 slices" }, { name: "Eggs", amount: "3" }, { name: "Milk", amount: "1/2 cup" }, { name: "Cinnamon", amount: "1 tsp" }, { name: "Maple syrup", amount: "1/4 cup" }], steps: ["Mix eggs, milk, cinnamon", "Dip bread slices", "Cook on buttered griddle", "Flip when golden", "Serve with syrup"], tags: ["Breakfast", "Sweet", "Classic"], cuisine: "French" },
  // 76-90 Seafood
  { title: "Shrimp Scampi", cookTime: "15 min", difficulty: "Easy", likes: 2900, comments: 198, ingredients: [{ name: "Shrimp", amount: "500g" }, { name: "Linguine", amount: "300g" }, { name: "Garlic", amount: "6 cloves" }, { name: "White wine", amount: "1/2 cup" }, { name: "Butter", amount: "3 tbsp" }], steps: ["Cook pasta", "Sauté garlic in butter", "Add shrimp", "Deglaze with wine", "Toss with pasta"], tags: ["Italian", "Seafood", "Quick"], cuisine: "Italian" },
  { title: "Fish Tacos", cookTime: "20 min", difficulty: "Easy", likes: 3400, comments: 234, ingredients: [{ name: "White fish", amount: "400g" }, { name: "Corn tortillas", amount: "8" }, { name: "Cabbage slaw", amount: "2 cups" }, { name: "Chipotle mayo", amount: "1/4 cup" }, { name: "Lime", amount: "2" }], steps: ["Season and grill fish", "Warm tortillas", "Make slaw", "Assemble tacos", "Drizzle with sauce"], tags: ["Mexican", "Seafood", "Fresh"], cuisine: "Mexican" },
  { title: "Salmon Teriyaki", cookTime: "20 min", difficulty: "Easy", likes: 3100, comments: 212, ingredients: [{ name: "Salmon fillets", amount: "4" }, { name: "Soy sauce", amount: "3 tbsp" }, { name: "Mirin", amount: "2 tbsp" }, { name: "Honey", amount: "1 tbsp" }, { name: "Rice", amount: "2 cups" }], steps: ["Make teriyaki glaze", "Pan sear salmon", "Glaze and broil", "Serve over rice"], tags: ["Japanese", "Seafood", "Healthy"], cuisine: "Japanese" },
  { title: "Coconut Shrimp", cookTime: "20 min", difficulty: "Easy", likes: 2200, comments: 156, ingredients: [{ name: "Shrimp", amount: "500g" }, { name: "Shredded coconut", amount: "1 cup" }, { name: "Panko", amount: "1/2 cup" }, { name: "Sweet chili sauce", amount: "1/2 cup" }], steps: ["Coat shrimp in coconut and panko", "Deep fry until golden", "Drain", "Serve with sweet chili"], tags: ["Appetizer", "Fried", "Seafood"], cuisine: "Thai" },
  { title: "Miso Glazed Cod", cookTime: "25 min", difficulty: "Medium", likes: 2500, comments: 178, ingredients: [{ name: "Cod fillets", amount: "4" }, { name: "White miso", amount: "3 tbsp" }, { name: "Mirin", amount: "2 tbsp" }, { name: "Sake", amount: "2 tbsp" }, { name: "Sugar", amount: "1 tbsp" }], steps: ["Mix miso glaze", "Marinate cod 2 hours", "Broil until caramelized", "Serve with rice"], tags: ["Japanese", "Seafood", "Elegant"], cuisine: "Japanese" },
  // 81-100 Various world cuisines
  { title: "Peri Peri Chicken", cookTime: "40 min", difficulty: "Medium", likes: 2900, comments: 198, ingredients: [{ name: "Chicken", amount: "1 whole" }, { name: "Peri peri sauce", amount: "1 cup" }, { name: "Lemon", amount: "2" }, { name: "Garlic", amount: "6 cloves" }], steps: ["Butterfly chicken", "Marinate in peri peri", "Grill 30 minutes", "Rest and serve"], tags: ["Portuguese", "Grilled", "Spicy"], cuisine: "Portuguese" },
  { title: "Jerk Chicken", cookTime: "45 min", difficulty: "Medium", likes: 3200, comments: 223, ingredients: [{ name: "Chicken thighs", amount: "8" }, { name: "Scotch bonnet", amount: "2" }, { name: "Allspice", amount: "1 tbsp" }, { name: "Thyme", amount: "4 sprigs" }, { name: "Soy sauce", amount: "2 tbsp" }], steps: ["Blend marinade", "Marinate overnight", "Grill low and slow", "Serve with rice and peas"], tags: ["Caribbean", "Grilled", "Spicy"], cuisine: "Jamaican" },
  { title: "Pierogi", cookTime: "60 min", difficulty: "Hard", likes: 1800, comments: 123, ingredients: [{ name: "Flour", amount: "2 cups" }, { name: "Potatoes", amount: "3" }, { name: "Cheddar", amount: "1 cup" }, { name: "Sour cream", amount: "1 cup" }, { name: "Onion", amount: "2" }], steps: ["Make dough", "Boil and mash potatoes", "Fill and seal dumplings", "Boil then pan fry", "Top with onions and sour cream"], tags: ["Polish", "Dumplings", "Comfort"], cuisine: "Polish" },
  { title: "Poke Bowl", cookTime: "15 min", difficulty: "Easy", likes: 3600, comments: 245, ingredients: [{ name: "Sushi rice", amount: "2 cups" }, { name: "Ahi tuna", amount: "300g" }, { name: "Soy sauce", amount: "2 tbsp" }, { name: "Avocado", amount: "1" }, { name: "Edamame", amount: "1/2 cup" }], steps: ["Cook sushi rice", "Cube tuna", "Marinate in soy and sesame", "Assemble bowls", "Add toppings"], tags: ["Hawaiian", "Bowl", "Fresh"], cuisine: "Hawaiian" },
  { title: "Arepas", cookTime: "20 min", difficulty: "Easy", likes: 1600, comments: 98, ingredients: [{ name: "Corn flour", amount: "2 cups" }, { name: "Water", amount: "2 cups" }, { name: "Cheese", amount: "1 cup" }, { name: "Black beans", amount: "1 cup" }], steps: ["Mix dough", "Form patties", "Cook on griddle", "Split and fill with cheese"], tags: ["Venezuelan", "Bread", "Gluten-free"], cuisine: "Venezuelan" },
  { title: "Goulash", cookTime: "90 min", difficulty: "Medium", likes: 1900, comments: 134, ingredients: [{ name: "Beef chuck", amount: "500g" }, { name: "Paprika", amount: "3 tbsp" }, { name: "Onions", amount: "3" }, { name: "Potatoes", amount: "3" }, { name: "Caraway seeds", amount: "1 tsp" }], steps: ["Brown beef", "Caramelize onions", "Add paprika and tomatoes", "Simmer 1 hour", "Add potatoes last 20 min"], tags: ["Hungarian", "Stew", "Hearty"], cuisine: "Hungarian" },
  { title: "Paella", cookTime: "45 min", difficulty: "Hard", likes: 3100, comments: 212, ingredients: [{ name: "Bomba rice", amount: "2 cups" }, { name: "Shrimp", amount: "300g" }, { name: "Chorizo", amount: "150g" }, { name: "Saffron", amount: "1 pinch" }, { name: "Chicken", amount: "300g" }], steps: ["Cook chicken and chorizo", "Add rice and saffron broth", "Arrange seafood on top", "Cook until socarrat forms", "Rest and serve"], tags: ["Spanish", "Rice", "Festive"], cuisine: "Spanish" },
  { title: "Beef Stroganoff", cookTime: "30 min", difficulty: "Medium", likes: 2400, comments: 167, ingredients: [{ name: "Beef sirloin", amount: "500g" }, { name: "Mushrooms", amount: "200g" }, { name: "Sour cream", amount: "1 cup" }, { name: "Egg noodles", amount: "300g" }, { name: "Onion", amount: "1" }], steps: ["Slice and sear beef", "Sauté mushrooms", "Make sauce", "Add sour cream", "Serve over noodles"], tags: ["Russian", "Pasta", "Creamy"], cuisine: "Russian" },
  // 89-100 Desserts & Sweets
  { title: "Tiramisu", cookTime: "30 min", difficulty: "Medium", likes: 4200, comments: 312, ingredients: [{ name: "Mascarpone", amount: "500g" }, { name: "Espresso", amount: "1 cup" }, { name: "Ladyfingers", amount: "24" }, { name: "Egg yolks", amount: "4" }, { name: "Cocoa powder", amount: "2 tbsp" }], steps: ["Make mascarpone cream", "Dip ladyfingers in espresso", "Layer cream and ladyfingers", "Chill 4 hours", "Dust with cocoa"], tags: ["Italian", "Dessert", "No-bake"], cuisine: "Italian" },
  { title: "Chocolate Lava Cake", cookTime: "20 min", difficulty: "Medium", likes: 3800, comments: 256, ingredients: [{ name: "Dark chocolate", amount: "200g" }, { name: "Butter", amount: "100g" }, { name: "Eggs", amount: "3" }, { name: "Sugar", amount: "1/4 cup" }, { name: "Flour", amount: "2 tbsp" }], steps: ["Melt chocolate and butter", "Whisk eggs and sugar", "Fold together with flour", "Bake 12 minutes at 425°F", "Invert and serve immediately"], tags: ["French", "Dessert", "Chocolate"], cuisine: "French" },
  { title: "Mochi", cookTime: "20 min", difficulty: "Easy", likes: 2100, comments: 145, ingredients: [{ name: "Glutinous rice flour", amount: "1 cup" }, { name: "Sugar", amount: "1/4 cup" }, { name: "Water", amount: "3/4 cup" }, { name: "Red bean paste", amount: "1/2 cup" }], steps: ["Mix flour, sugar, water", "Microwave in intervals", "Form into balls", "Fill with red bean paste", "Dust with cornstarch"], tags: ["Japanese", "Dessert", "Sweet"], cuisine: "Japanese" },
  { title: "Panna Cotta", cookTime: "15 min", difficulty: "Easy", likes: 2500, comments: 178, ingredients: [{ name: "Heavy cream", amount: "2 cups" }, { name: "Sugar", amount: "1/3 cup" }, { name: "Gelatin", amount: "2 tsp" }, { name: "Vanilla", amount: "1 tsp" }, { name: "Berry sauce", amount: "1/2 cup" }], steps: ["Bloom gelatin", "Heat cream and sugar", "Add gelatin", "Pour into molds", "Chill and unmold"], tags: ["Italian", "Dessert", "Elegant"], cuisine: "Italian" },
  { title: "Matcha Swiss Roll", cookTime: "30 min", difficulty: "Medium", likes: 1800, comments: 123, ingredients: [{ name: "Eggs", amount: "4" }, { name: "Sugar", amount: "1/2 cup" }, { name: "Flour", amount: "1/2 cup" }, { name: "Matcha powder", amount: "2 tbsp" }, { name: "Whipped cream", amount: "1 cup" }], steps: ["Make matcha sponge", "Bake thin sheet", "Roll while warm", "Cool completely", "Unroll, fill with cream, re-roll"], tags: ["Japanese", "Dessert", "Matcha"], cuisine: "Japanese" },
  // 94-110 Healthy/Vegan
  { title: "Buddha Bowl", cookTime: "25 min", difficulty: "Easy", likes: 2800, comments: 189, ingredients: [{ name: "Quinoa", amount: "1 cup" }, { name: "Roasted sweet potato", amount: "1" }, { name: "Chickpeas", amount: "1 can" }, { name: "Avocado", amount: "1" }, { name: "Tahini dressing", amount: "1/4 cup" }], steps: ["Cook quinoa", "Roast sweet potato and chickpeas", "Slice avocado", "Assemble bowl", "Drizzle tahini"], tags: ["Vegan", "Bowl", "Healthy"], cuisine: "American" },
  { title: "Cauliflower Wings", cookTime: "30 min", difficulty: "Easy", likes: 1900, comments: 134, ingredients: [{ name: "Cauliflower", amount: "1 head" }, { name: "Hot sauce", amount: "1/2 cup" }, { name: "Flour", amount: "1 cup" }, { name: "Butter", amount: "2 tbsp" }], steps: ["Cut into florets", "Batter and bake", "Make buffalo sauce", "Toss cauliflower", "Serve with ranch"], tags: ["Vegan", "Appetizer", "Spicy"], cuisine: "American" },
  { title: "Lentil Bolognese", cookTime: "35 min", difficulty: "Easy", likes: 2100, comments: 145, ingredients: [{ name: "Green lentils", amount: "1 cup" }, { name: "Crushed tomatoes", amount: "2 cans" }, { name: "Carrots", amount: "2" }, { name: "Celery", amount: "2 stalks" }, { name: "Pasta", amount: "400g" }], steps: ["Sauté mirepoix", "Add lentils and tomatoes", "Simmer 25 minutes", "Cook pasta", "Combine and serve"], tags: ["Vegan", "Pasta", "Protein"], cuisine: "Italian" },
  { title: "Overnight Oats", cookTime: "5 min", difficulty: "Easy", likes: 2400, comments: 167, ingredients: [{ name: "Rolled oats", amount: "1/2 cup" }, { name: "Milk", amount: "1/2 cup" }, { name: "Yogurt", amount: "1/4 cup" }, { name: "Chia seeds", amount: "1 tbsp" }, { name: "Berries", amount: "1/2 cup" }], steps: ["Mix oats, milk, yogurt", "Add chia seeds", "Refrigerate overnight", "Top with berries", "Enjoy cold"], tags: ["Breakfast", "Healthy", "Meal-prep"], cuisine: "American" },
  { title: "Smoothie Bowl", cookTime: "5 min", difficulty: "Easy", likes: 2100, comments: 134, ingredients: [{ name: "Frozen berries", amount: "2 cups" }, { name: "Banana", amount: "1" }, { name: "Almond milk", amount: "1/2 cup" }, { name: "Granola", amount: "1/4 cup" }], steps: ["Blend berries and banana thick", "Pour into bowl", "Top with granola", "Add fresh fruit"], tags: ["Breakfast", "Healthy", "Quick"], cuisine: "American" },
  { title: "Stuffed Bell Peppers", cookTime: "40 min", difficulty: "Easy", likes: 1800, comments: 112, ingredients: [{ name: "Bell peppers", amount: "4" }, { name: "Ground turkey", amount: "400g" }, { name: "Rice", amount: "1 cup" }, { name: "Tomato sauce", amount: "1 cup" }, { name: "Cheese", amount: "1 cup" }], steps: ["Cook rice and meat", "Mix filling", "Stuff peppers", "Top with sauce and cheese", "Bake 25 minutes"], tags: ["Healthy", "Baked", "Protein"], cuisine: "American" },
  // 100-115 More world
  { title: "Doner Kebab", cookTime: "30 min", difficulty: "Medium", likes: 3400, comments: 234, ingredients: [{ name: "Lamb/beef mix", amount: "500g" }, { name: "Pita bread", amount: "4" }, { name: "Yogurt sauce", amount: "1/2 cup" }, { name: "Tomatoes", amount: "2" }, { name: "Onion", amount: "1" }], steps: ["Season and shape meat", "Grill or roast", "Slice thinly", "Warm pita", "Assemble with toppings"], tags: ["Turkish", "Wrap", "Street food"], cuisine: "Turkish" },
  { title: "Dim Sum Siu Mai", cookTime: "30 min", difficulty: "Medium", likes: 2200, comments: 156, ingredients: [{ name: "Ground pork", amount: "300g" }, { name: "Shrimp", amount: "100g" }, { name: "Wonton wrappers", amount: "24" }, { name: "Soy sauce", amount: "1 tbsp" }], steps: ["Mix pork and shrimp filling", "Wrap in wonton skins", "Steam 10 minutes", "Serve with chili oil"], tags: ["Chinese", "Dim sum", "Steamed"], cuisine: "Chinese" },
  { title: "Ethiopian Injera Platter", cookTime: "45 min", difficulty: "Medium", likes: 1600, comments: 98, ingredients: [{ name: "Injera bread", amount: "4" }, { name: "Red lentils", amount: "1 cup" }, { name: "Berbere spice", amount: "2 tbsp" }, { name: "Cabbage", amount: "1/2" }], steps: ["Make misir wot (lentil stew)", "Cook cabbage side", "Warm injera", "Arrange on platter", "Eat with hands"], tags: ["Ethiopian", "Vegan", "Communal"], cuisine: "Ethiopian" },
  { title: "Bao Buns", cookTime: "45 min", difficulty: "Medium", likes: 2800, comments: 189, ingredients: [{ name: "Flour", amount: "2 cups" }, { name: "Yeast", amount: "1 tsp" }, { name: "Pork belly", amount: "300g" }, { name: "Hoisin sauce", amount: "1/4 cup" }, { name: "Pickled cucumber", amount: "1/2 cup" }], steps: ["Make dough and proof", "Braise pork belly", "Shape and steam buns", "Fill with pork", "Add hoisin and pickles"], tags: ["Chinese", "Street food", "Steamed"], cuisine: "Chinese" },
  { title: "Takoyaki", cookTime: "20 min", difficulty: "Medium", likes: 2100, comments: 145, ingredients: [{ name: "Takoyaki batter", amount: "2 cups" }, { name: "Octopus", amount: "200g" }, { name: "Green onion", amount: "3 stalks" }, { name: "Takoyaki sauce", amount: "1/4 cup" }, { name: "Bonito flakes", amount: "1/4 cup" }], steps: ["Heat takoyaki pan", "Pour batter", "Add octopus pieces", "Rotate until round", "Top with sauce and bonito"], tags: ["Japanese", "Street food", "Snack"], cuisine: "Japanese" },
  { title: "Croissants", cookTime: "180 min", difficulty: "Hard", likes: 2600, comments: 178, ingredients: [{ name: "Flour", amount: "3 cups" }, { name: "Butter block", amount: "250g" }, { name: "Yeast", amount: "2 tsp" }, { name: "Milk", amount: "1 cup" }, { name: "Sugar", amount: "2 tbsp" }], steps: ["Make détrempe", "Enclose butter", "Fold 3 times", "Chill between folds", "Shape and proof", "Bake golden"], tags: ["French", "Pastry", "Classic"], cuisine: "French" },
  { title: "Tom Kha Gai", cookTime: "25 min", difficulty: "Easy", likes: 2300, comments: 167, ingredients: [{ name: "Chicken", amount: "300g" }, { name: "Coconut milk", amount: "2 cans" }, { name: "Galangal", amount: "2 inches" }, { name: "Lemongrass", amount: "2 stalks" }, { name: "Mushrooms", amount: "1 cup" }], steps: ["Simmer coconut milk with aromatics", "Add chicken", "Add mushrooms", "Season with fish sauce and lime", "Serve hot"], tags: ["Thai", "Soup", "Coconut"], cuisine: "Thai" },
  { title: "Cacio e Pepe", cookTime: "15 min", difficulty: "Medium", likes: 3800, comments: 267, ingredients: [{ name: "Tonnarelli pasta", amount: "400g" }, { name: "Pecorino Romano", amount: "2 cups" }, { name: "Black pepper", amount: "2 tbsp" }], steps: ["Cook pasta very al dente", "Toast pepper", "Create cheese paste with pasta water", "Toss pasta vigorously", "Serve immediately"], tags: ["Italian", "Pasta", "Minimal"], cuisine: "Italian" },
  { title: "Massaman Curry", cookTime: "45 min", difficulty: "Medium", likes: 2700, comments: 189, ingredients: [{ name: "Beef", amount: "500g" }, { name: "Massaman paste", amount: "3 tbsp" }, { name: "Coconut milk", amount: "2 cans" }, { name: "Potatoes", amount: "2" }, { name: "Peanuts", amount: "1/4 cup" }], steps: ["Fry curry paste", "Add coconut milk", "Add beef and potatoes", "Simmer 30 minutes", "Add peanuts and serve"], tags: ["Thai", "Curry", "Rich"], cuisine: "Thai" },
  { title: "Xiao Long Bao", cookTime: "60 min", difficulty: "Hard", likes: 3400, comments: 234, ingredients: [{ name: "Flour", amount: "2 cups" }, { name: "Ground pork", amount: "300g" }, { name: "Gelatin broth", amount: "1 cup" }, { name: "Ginger", amount: "1 tbsp" }, { name: "Soy sauce", amount: "2 tbsp" }], steps: ["Make aspic from broth", "Mix filling with aspic", "Make thin dough", "Wrap with pleats", "Steam 8 minutes"], tags: ["Chinese", "Dumplings", "Steamed"], cuisine: "Chinese" },
  // 109-125 More
  { title: "Chicken Tikka", cookTime: "30 min", difficulty: "Easy", likes: 3100, comments: 212, ingredients: [{ name: "Chicken", amount: "500g" }, { name: "Yogurt", amount: "1 cup" }, { name: "Tikka spice", amount: "2 tbsp" }, { name: "Lemon", amount: "1" }], steps: ["Marinate chicken in yogurt and spices", "Thread onto skewers", "Grill until charred", "Serve with mint chutney"], tags: ["Indian", "Grilled", "Protein"], cuisine: "Indian" },
  { title: "Okonomiyaki", cookTime: "20 min", difficulty: "Easy", likes: 2000, comments: 145, ingredients: [{ name: "Cabbage", amount: "3 cups" }, { name: "Flour", amount: "1 cup" }, { name: "Eggs", amount: "2" }, { name: "Pork belly", amount: "100g" }, { name: "Okonomiyaki sauce", amount: "1/4 cup" }], steps: ["Mix batter with cabbage", "Pour onto griddle", "Top with pork", "Flip carefully", "Add sauce and mayo"], tags: ["Japanese", "Pancake", "Street food"], cuisine: "Japanese" },
  { title: "Bruschetta", cookTime: "10 min", difficulty: "Easy", likes: 1800, comments: 112, ingredients: [{ name: "Baguette", amount: "1" }, { name: "Tomatoes", amount: "4" }, { name: "Basil", amount: "1 bunch" }, { name: "Garlic", amount: "2 cloves" }, { name: "Olive oil", amount: "2 tbsp" }], steps: ["Dice tomatoes", "Mix with basil and garlic", "Toast bread slices", "Rub with garlic", "Top with tomato mixture"], tags: ["Italian", "Appetizer", "Fresh"], cuisine: "Italian" },
  { title: "Chicken Adobo", cookTime: "40 min", difficulty: "Easy", likes: 2700, comments: 189, ingredients: [{ name: "Chicken thighs", amount: "6" }, { name: "Soy sauce", amount: "1/3 cup" }, { name: "Vinegar", amount: "1/3 cup" }, { name: "Garlic", amount: "8 cloves" }, { name: "Bay leaves", amount: "3" }], steps: ["Combine soy, vinegar, garlic", "Add chicken and marinate", "Braise until tender", "Reduce sauce", "Serve over rice"], tags: ["Filipino", "Braised", "Classic"], cuisine: "Filipino" },
  { title: "Chimichurri Steak", cookTime: "20 min", difficulty: "Medium", likes: 3500, comments: 234, ingredients: [{ name: "Ribeye steak", amount: "2" }, { name: "Parsley", amount: "1 cup" }, { name: "Oregano", amount: "1 tbsp" }, { name: "Garlic", amount: "4 cloves" }, { name: "Red wine vinegar", amount: "2 tbsp" }], steps: ["Blend chimichurri", "Season steaks", "Grill to desired doneness", "Rest 5 minutes", "Serve with chimichurri"], tags: ["Argentine", "Grilled", "Steak"], cuisine: "Argentine" },
  { title: "Dalgona Coffee", cookTime: "5 min", difficulty: "Easy", likes: 4100, comments: 298, ingredients: [{ name: "Instant coffee", amount: "2 tbsp" }, { name: "Sugar", amount: "2 tbsp" }, { name: "Hot water", amount: "2 tbsp" }, { name: "Milk", amount: "1 cup" }], steps: ["Whisk coffee, sugar, water until fluffy", "Fill glass with milk and ice", "Spoon coffee foam on top", "Stir before drinking"], tags: ["Korean", "Drink", "Viral"], cuisine: "Korean" },
  { title: "Croquetas", cookTime: "40 min", difficulty: "Medium", likes: 2000, comments: 145, ingredients: [{ name: "Ham", amount: "100g" }, { name: "Flour", amount: "1/3 cup" }, { name: "Milk", amount: "2 cups" }, { name: "Butter", amount: "3 tbsp" }, { name: "Breadcrumbs", amount: "1 cup" }], steps: ["Make thick béchamel", "Mix in ham", "Chill until firm", "Shape and bread", "Fry until golden"], tags: ["Spanish", "Fried", "Tapas"], cuisine: "Spanish" },
  { title: "Wonton Soup", cookTime: "25 min", difficulty: "Medium", likes: 2300, comments: 167, ingredients: [{ name: "Wonton wrappers", amount: "30" }, { name: "Ground pork", amount: "200g" }, { name: "Shrimp", amount: "100g" }, { name: "Chicken broth", amount: "4 cups" }, { name: "Bok choy", amount: "2" }], steps: ["Make filling", "Wrap wontons", "Boil in broth", "Add bok choy", "Serve hot"], tags: ["Chinese", "Soup", "Dumplings"], cuisine: "Chinese" },
  { title: "Galbi", cookTime: "25 min", difficulty: "Easy", likes: 2800, comments: 189, ingredients: [{ name: "Beef short ribs", amount: "1 kg" }, { name: "Soy sauce", amount: "1/3 cup" }, { name: "Sugar", amount: "2 tbsp" }, { name: "Sesame oil", amount: "1 tbsp" }, { name: "Pear", amount: "1/2" }], steps: ["Blend marinade with pear", "Marinate ribs 4 hours", "Grill on high heat", "Cut between bones", "Serve with banchan"], tags: ["Korean", "BBQ", "Grilled"], cuisine: "Korean" },
  // 118-135 More variety
  { title: "Shakshuka Verde", cookTime: "20 min", difficulty: "Easy", likes: 1600, comments: 98, ingredients: [{ name: "Eggs", amount: "4" }, { name: "Tomatillos", amount: "6" }, { name: "Jalapeño", amount: "2" }, { name: "Cilantro", amount: "1 bunch" }, { name: "Feta", amount: "100g" }], steps: ["Roast tomatillos and jalapeños", "Blend green sauce", "Pour in pan and heat", "Crack eggs into sauce", "Cover and cook"], tags: ["Mexican", "Breakfast", "One-pan"], cuisine: "Mexican" },
  { title: "Katsu Sando", cookTime: "20 min", difficulty: "Easy", likes: 2900, comments: 198, ingredients: [{ name: "Pork loin", amount: "2" }, { name: "Panko", amount: "1 cup" }, { name: "Shoku bread", amount: "4 slices" }, { name: "Tonkatsu sauce", amount: "1/4 cup" }, { name: "Cabbage", amount: "1 cup" }], steps: ["Bread and fry pork", "Slice and sauce", "Layer on bread with cabbage", "Press and cut"], tags: ["Japanese", "Sandwich", "Fried"], cuisine: "Japanese" },
  { title: "Chicken Souvlaki", cookTime: "20 min", difficulty: "Easy", likes: 2400, comments: 167, ingredients: [{ name: "Chicken breast", amount: "500g" }, { name: "Lemon", amount: "2" }, { name: "Oregano", amount: "1 tbsp" }, { name: "Pita bread", amount: "4" }, { name: "Tzatziki", amount: "1 cup" }], steps: ["Marinate chicken cubes", "Thread onto skewers", "Grill until done", "Serve in pita", "Add tzatziki and veggies"], tags: ["Greek", "Grilled", "Wrap"], cuisine: "Greek" },
  { title: "Miso Ramen", cookTime: "35 min", difficulty: "Medium", likes: 3600, comments: 245, ingredients: [{ name: "Ramen noodles", amount: "2 packs" }, { name: "White miso", amount: "3 tbsp" }, { name: "Pork belly", amount: "200g" }, { name: "Corn", amount: "1/2 cup" }, { name: "Butter", amount: "1 tbsp" }], steps: ["Make miso broth", "Cook chashu pork", "Cook noodles", "Assemble bowls", "Top with corn and butter"], tags: ["Japanese", "Ramen", "Comfort"], cuisine: "Japanese" },
  { title: "Pupusas", cookTime: "30 min", difficulty: "Easy", likes: 1800, comments: 112, ingredients: [{ name: "Masa harina", amount: "2 cups" }, { name: "Cheese", amount: "1 cup" }, { name: "Refried beans", amount: "1 cup" }, { name: "Curtido", amount: "1 cup" }], steps: ["Make masa dough", "Fill with cheese and beans", "Form thick tortillas", "Cook on griddle", "Serve with curtido"], tags: ["Salvadoran", "Street food", "Cheese"], cuisine: "Salvadoran" },
  { title: "Peking Duck", cookTime: "180 min", difficulty: "Hard", likes: 2900, comments: 198, ingredients: [{ name: "Whole duck", amount: "1" }, { name: "Maltose", amount: "2 tbsp" }, { name: "Pancakes", amount: "12" }, { name: "Hoisin sauce", amount: "1/4 cup" }, { name: "Scallions", amount: "6" }], steps: ["Air dry duck overnight", "Glaze with maltose", "Roast at high heat", "Carve tableside", "Serve with pancakes"], tags: ["Chinese", "Roasted", "Festive"], cuisine: "Chinese" },
  { title: "Gazpacho", cookTime: "10 min", difficulty: "Easy", likes: 1500, comments: 89, ingredients: [{ name: "Tomatoes", amount: "6" }, { name: "Cucumber", amount: "1" }, { name: "Bell pepper", amount: "1" }, { name: "Olive oil", amount: "3 tbsp" }, { name: "Sherry vinegar", amount: "2 tbsp" }], steps: ["Chop all vegetables", "Blend until smooth", "Season", "Chill thoroughly", "Serve cold with garnish"], tags: ["Spanish", "Soup", "Cold"], cuisine: "Spanish" },
  { title: "Biscuits & Gravy", cookTime: "25 min", difficulty: "Easy", likes: 2600, comments: 178, ingredients: [{ name: "Biscuits", amount: "4" }, { name: "Pork sausage", amount: "300g" }, { name: "Flour", amount: "2 tbsp" }, { name: "Milk", amount: "2 cups" }], steps: ["Bake biscuits", "Brown sausage", "Make gravy with drippings", "Pour over split biscuits"], tags: ["American", "Breakfast", "Southern"], cuisine: "American" },
  { title: "Tandoori Chicken", cookTime: "35 min", difficulty: "Easy", likes: 3200, comments: 212, ingredients: [{ name: "Chicken legs", amount: "8" }, { name: "Yogurt", amount: "1 cup" }, { name: "Tandoori masala", amount: "3 tbsp" }, { name: "Lemon", amount: "2" }, { name: "Ginger-garlic paste", amount: "2 tbsp" }], steps: ["Score chicken", "Mix yogurt marinade", "Marinate 4 hours", "Grill or bake hot", "Serve with naan"], tags: ["Indian", "Grilled", "Classic"], cuisine: "Indian" },
  { title: "Chocolate Chip Cookies", cookTime: "25 min", difficulty: "Easy", likes: 4800, comments: 356, ingredients: [{ name: "Butter", amount: "1 cup" }, { name: "Sugar", amount: "3/4 cup" }, { name: "Brown sugar", amount: "3/4 cup" }, { name: "Flour", amount: "2.25 cups" }, { name: "Chocolate chips", amount: "2 cups" }], steps: ["Cream butter and sugars", "Add eggs and vanilla", "Mix in flour", "Fold in chips", "Bake at 375°F 10 min"], tags: ["American", "Dessert", "Baking"], cuisine: "American" },
  // 128-150+ Fill remaining
  { title: "Sushi Rolls", cookTime: "40 min", difficulty: "Medium", likes: 3800, comments: 267, ingredients: [{ name: "Sushi rice", amount: "2 cups" }, { name: "Nori", amount: "5 sheets" }, { name: "Salmon", amount: "200g" }, { name: "Avocado", amount: "1" }, { name: "Cucumber", amount: "1" }], steps: ["Season rice with vinegar", "Place nori on mat", "Spread rice", "Add fillings", "Roll tightly and slice"], tags: ["Japanese", "Sushi", "Classic"], cuisine: "Japanese" },
  { title: "Carnitas", cookTime: "180 min", difficulty: "Medium", likes: 3200, comments: 212, ingredients: [{ name: "Pork shoulder", amount: "1.5 kg" }, { name: "Orange juice", amount: "1 cup" }, { name: "Cumin", amount: "1 tbsp" }, { name: "Oregano", amount: "1 tbsp" }, { name: "Lard", amount: "2 tbsp" }], steps: ["Season pork", "Braise with orange juice", "Shred meat", "Crisp under broiler", "Serve in tacos"], tags: ["Mexican", "Slow-cook", "Pork"], cuisine: "Mexican" },
  { title: "Clafoutis", cookTime: "40 min", difficulty: "Easy", likes: 1400, comments: 89, ingredients: [{ name: "Cherries", amount: "2 cups" }, { name: "Eggs", amount: "3" }, { name: "Flour", amount: "1/2 cup" }, { name: "Milk", amount: "1 cup" }, { name: "Sugar", amount: "1/3 cup" }], steps: ["Arrange cherries in dish", "Blend batter", "Pour over fruit", "Bake 35 minutes", "Dust with sugar"], tags: ["French", "Dessert", "Fruity"], cuisine: "French" },
  { title: "Khao Soi", cookTime: "35 min", difficulty: "Medium", likes: 2400, comments: 167, ingredients: [{ name: "Egg noodles", amount: "300g" }, { name: "Coconut milk", amount: "2 cans" }, { name: "Curry paste", amount: "3 tbsp" }, { name: "Chicken", amount: "400g" }, { name: "Crispy noodles", amount: "1 cup" }], steps: ["Make curry broth", "Cook chicken in broth", "Boil noodles", "Assemble bowls", "Top with crispy noodles"], tags: ["Thai", "Curry", "Noodles"], cuisine: "Thai" },
  { title: "Crab Rangoon", cookTime: "20 min", difficulty: "Easy", likes: 2100, comments: 145, ingredients: [{ name: "Cream cheese", amount: "8 oz" }, { name: "Crab meat", amount: "100g" }, { name: "Wonton wrappers", amount: "24" }, { name: "Green onion", amount: "2" }], steps: ["Mix filling", "Place in wrappers", "Fold into triangles", "Deep fry", "Serve with sweet chili"], tags: ["American-Chinese", "Fried", "Appetizer"], cuisine: "Chinese" },
  { title: "Bangers & Mash", cookTime: "30 min", difficulty: "Easy", likes: 1900, comments: 134, ingredients: [{ name: "Pork sausages", amount: "6" }, { name: "Potatoes", amount: "4" }, { name: "Butter", amount: "3 tbsp" }, { name: "Onion gravy", amount: "2 cups" }], steps: ["Cook sausages", "Boil and mash potatoes", "Make onion gravy", "Plate and pour gravy"], tags: ["British", "Comfort", "Classic"], cuisine: "British" },
  { title: "Congee", cookTime: "60 min", difficulty: "Easy", likes: 1600, comments: 98, ingredients: [{ name: "Rice", amount: "1 cup" }, { name: "Chicken broth", amount: "8 cups" }, { name: "Ginger", amount: "2 inches" }, { name: "Century egg", amount: "2" }, { name: "Green onion", amount: "3" }], steps: ["Simmer rice in broth", "Stir occasionally", "Cook until thick and creamy", "Top with egg and ginger", "Garnish with scallions"], tags: ["Chinese", "Porridge", "Comfort"], cuisine: "Chinese" },
  { title: "Crêpes", cookTime: "20 min", difficulty: "Easy", likes: 2800, comments: 189, ingredients: [{ name: "Flour", amount: "1 cup" }, { name: "Eggs", amount: "2" }, { name: "Milk", amount: "1 cup" }, { name: "Butter", amount: "2 tbsp" }, { name: "Nutella", amount: "1/2 cup" }], steps: ["Mix batter smooth", "Rest 30 minutes", "Cook thin on hot pan", "Fill with Nutella", "Fold and serve"], tags: ["French", "Dessert", "Sweet"], cuisine: "French" },
  { title: "Beef Pho", cookTime: "45 min", difficulty: "Medium", likes: 3600, comments: 245, ingredients: [{ name: "Rice noodles", amount: "300g" }, { name: "Beef sirloin", amount: "300g" }, { name: "Star anise", amount: "3" }, { name: "Cinnamon", amount: "1 stick" }, { name: "Bean sprouts", amount: "1 cup" }], steps: ["Make spiced broth", "Cook noodles", "Slice beef paper thin", "Pour hot broth over beef", "Add fresh herbs"], tags: ["Vietnamese", "Soup", "Classic"], cuisine: "Vietnamese" },
  { title: "Arancini", cookTime: "40 min", difficulty: "Medium", likes: 2200, comments: 156, ingredients: [{ name: "Risotto", amount: "3 cups" }, { name: "Mozzarella", amount: "100g" }, { name: "Breadcrumbs", amount: "1 cup" }, { name: "Marinara", amount: "1 cup" }], steps: ["Chill leftover risotto", "Form balls around mozzarella", "Bread and fry", "Drain on paper towels", "Serve with marinara"], tags: ["Italian", "Fried", "Appetizer"], cuisine: "Italian" },
  { title: "Lamb Tagine", cookTime: "120 min", difficulty: "Medium", likes: 2000, comments: 145, ingredients: [{ name: "Lamb shoulder", amount: "500g" }, { name: "Dried apricots", amount: "1/2 cup" }, { name: "Chickpeas", amount: "1 can" }, { name: "Ras el hanout", amount: "2 tbsp" }, { name: "Honey", amount: "1 tbsp" }], steps: ["Brown lamb", "Add spices and onions", "Add broth and fruit", "Slow cook 90 minutes", "Serve with couscous"], tags: ["Moroccan", "Stew", "Aromatic"], cuisine: "Moroccan" },
  { title: "Cornbread", cookTime: "25 min", difficulty: "Easy", likes: 1700, comments: 112, ingredients: [{ name: "Cornmeal", amount: "1 cup" }, { name: "Flour", amount: "1 cup" }, { name: "Buttermilk", amount: "1 cup" }, { name: "Eggs", amount: "2" }, { name: "Honey", amount: "2 tbsp" }], steps: ["Mix dry ingredients", "Add wet ingredients", "Pour in hot skillet", "Bake 20 minutes", "Serve with butter and honey"], tags: ["American", "Bread", "Southern"], cuisine: "American" },
  { title: "Lobster Bisque", cookTime: "45 min", difficulty: "Hard", likes: 2500, comments: 178, ingredients: [{ name: "Lobster shells", amount: "from 2 lobsters" }, { name: "Cream", amount: "1 cup" }, { name: "Tomato paste", amount: "2 tbsp" }, { name: "Brandy", amount: "1/4 cup" }, { name: "Butter", amount: "3 tbsp" }], steps: ["Roast shells", "Make stock", "Add cream and tomato paste", "Flambé with brandy", "Strain and serve"], tags: ["French", "Soup", "Elegant"], cuisine: "French" },
  { title: "Chicken Parmesan", cookTime: "30 min", difficulty: "Medium", likes: 4100, comments: 298, ingredients: [{ name: "Chicken breast", amount: "2" }, { name: "Marinara sauce", amount: "1 cup" }, { name: "Mozzarella", amount: "1 cup" }, { name: "Parmesan", amount: "1/2 cup" }, { name: "Breadcrumbs", amount: "1 cup" }], steps: ["Bread and fry chicken", "Top with sauce", "Add cheese", "Broil until melted", "Serve with pasta"], tags: ["Italian-American", "Fried", "Cheese"], cuisine: "Italian" },
  { title: "Jambalaya", cookTime: "40 min", difficulty: "Medium", likes: 2800, comments: 189, ingredients: [{ name: "Rice", amount: "2 cups" }, { name: "Andouille sausage", amount: "200g" }, { name: "Shrimp", amount: "200g" }, { name: "Bell pepper", amount: "1" }, { name: "Cajun seasoning", amount: "2 tbsp" }], steps: ["Cook trinity (onion, celery, pepper)", "Add sausage", "Add rice and broth", "Cook until rice done", "Add shrimp last 5 min"], tags: ["Cajun", "Rice", "One-pot"], cuisine: "American" },
  { title: "Katsu Curry", cookTime: "30 min", difficulty: "Easy", likes: 3400, comments: 234, ingredients: [{ name: "Chicken breast", amount: "2" }, { name: "Panko", amount: "1 cup" }, { name: "Japanese curry blocks", amount: "4" }, { name: "Rice", amount: "2 cups" }, { name: "Carrots", amount: "2" }], steps: ["Bread and fry chicken", "Make curry sauce", "Cook rice", "Slice katsu", "Serve curry over rice"], tags: ["Japanese", "Curry", "Comfort"], cuisine: "Japanese" },
  { title: "Bolognese", cookTime: "90 min", difficulty: "Medium", likes: 4500, comments: 334, ingredients: [{ name: "Ground beef", amount: "500g" }, { name: "San Marzano tomatoes", amount: "2 cans" }, { name: "Carrots", amount: "2" }, { name: "Celery", amount: "2 stalks" }, { name: "Red wine", amount: "1 cup" }], steps: ["Sauté mirepoix", "Brown meat", "Add wine and reduce", "Add tomatoes", "Simmer 60 minutes"], tags: ["Italian", "Pasta", "Classic"], cuisine: "Italian" },
  { title: "Fried Plantains", cookTime: "10 min", difficulty: "Easy", likes: 1800, comments: 112, ingredients: [{ name: "Ripe plantains", amount: "3" }, { name: "Oil", amount: "for frying" }, { name: "Salt", amount: "pinch" }], steps: ["Peel and slice plantains", "Heat oil", "Fry until golden", "Drain", "Sprinkle salt"], tags: ["Caribbean", "Side", "Quick"], cuisine: "Caribbean" },
  { title: "Eggs Florentine", cookTime: "20 min", difficulty: "Medium", likes: 2100, comments: 145, ingredients: [{ name: "English muffins", amount: "2" }, { name: "Eggs", amount: "4" }, { name: "Spinach", amount: "2 cups" }, { name: "Hollandaise", amount: "1 cup" }], steps: ["Sauté spinach", "Toast muffins", "Poach eggs", "Layer spinach and eggs", "Pour hollandaise"], tags: ["Brunch", "Vegetarian", "Elegant"], cuisine: "American" },
  { title: "Coconut Curry Lentils", cookTime: "30 min", difficulty: "Easy", likes: 2400, comments: 167, ingredients: [{ name: "Red lentils", amount: "1 cup" }, { name: "Coconut milk", amount: "1 can" }, { name: "Curry powder", amount: "2 tbsp" }, { name: "Spinach", amount: "2 cups" }], steps: ["Cook lentils", "Add coconut milk and curry", "Simmer 15 minutes", "Stir in spinach", "Serve over rice"], tags: ["Vegan", "Curry", "Healthy"], cuisine: "Indian" },
  { title: "Tonkatsu", cookTime: "20 min", difficulty: "Easy", likes: 2900, comments: 198, ingredients: [{ name: "Pork loin", amount: "2" }, { name: "Panko", amount: "1 cup" }, { name: "Tonkatsu sauce", amount: "1/4 cup" }, { name: "Cabbage", amount: "2 cups" }, { name: "Rice", amount: "2 cups" }], steps: ["Tenderize pork", "Bread with panko", "Deep fry until golden", "Slice and serve", "Add sauce and cabbage"], tags: ["Japanese", "Fried", "Classic"], cuisine: "Japanese" },
  { title: "Cinnamon Rolls", cookTime: "120 min", difficulty: "Medium", likes: 3800, comments: 267, ingredients: [{ name: "Flour", amount: "3 cups" }, { name: "Butter", amount: "1/2 cup" }, { name: "Cinnamon", amount: "2 tbsp" }, { name: "Brown sugar", amount: "3/4 cup" }, { name: "Cream cheese frosting", amount: "1 cup" }], steps: ["Make enriched dough", "Roll out and fill", "Roll up tightly", "Slice and proof", "Bake and frost"], tags: ["American", "Baking", "Sweet"], cuisine: "American" },
  { title: "Sesame Noodles", cookTime: "15 min", difficulty: "Easy", likes: 2600, comments: 178, ingredients: [{ name: "Lo mein noodles", amount: "300g" }, { name: "Sesame paste", amount: "3 tbsp" }, { name: "Soy sauce", amount: "2 tbsp" }, { name: "Chili oil", amount: "1 tbsp" }, { name: "Cucumber", amount: "1" }], steps: ["Cook noodles and chill", "Mix sauce", "Toss noodles with sauce", "Top with cucumber", "Garnish with sesame"], tags: ["Chinese", "Cold", "Quick"], cuisine: "Chinese" },
  { title: "Mole Poblano", cookTime: "90 min", difficulty: "Hard", likes: 2200, comments: 156, ingredients: [{ name: "Dried chilis", amount: "4 varieties" }, { name: "Chocolate", amount: "30g" }, { name: "Chicken", amount: "1 whole" }, { name: "Sesame seeds", amount: "2 tbsp" }, { name: "Spices", amount: "assorted" }], steps: ["Toast and soak chilis", "Blend complex sauce", "Simmer 45 minutes", "Add chocolate", "Serve over chicken"], tags: ["Mexican", "Complex", "Classic"], cuisine: "Mexican" },
];

export const recipes: Recipe[] = recipeTemplates.map((r, i) => ({
  ...r,
  id: String(i + 1),
  image: pick(i),
  author: a(i).name,
  authorAvatar: a(i).avatar,
}));

export const mascotMessages = {
  import: [
    "Nice find! Let's turn that video into dinner 🦝",
    "Ooh I love this one! Let me break it down for you 🦝🍳",
    "Another banger recipe spotted! 🦝🔥",
  ],
  scan: [
    "Looks like you've got the start of something good.",
    "Let me see what we're working with here... 🦝👀",
    "I spy some delicious possibilities! 🦝",
  ],
  cookTogether: [
    "Cooking with friends? That's elite chef behavior 🦝🔥",
    "Squad cooking activated! Let's gooo 🦝",
    "Nothing beats cooking with the crew! 🦝❤️",
  ],
  cooking: [
    "You got this, chef! 🦝",
    "Looking good! Keep stirring 🦝🥄",
    "Almost there! The kitchen smells amazing 🦝",
  ],
  welcome: [
    "Hey chef! What are we cooking today? 🦝",
    "Welcome back! Your kitchen awaits 🦝🍽️",
  ],
};

export function getRandomMascotMessage(category: keyof typeof mascotMessages): string {
  const messages = mascotMessages[category];
  return messages[Math.floor(Math.random() * messages.length)];
}
